function getBridge(){return window.AstrBotPluginPage||null}
async function waitBridge(){for(let i=0;i<30;i++){const b=getBridge();if(b&&typeof b.ready==='function'){await b.ready();return}await new Promise(r=>setTimeout(r,100))}throw new Error('AstrBot Plugin Page Bridge 未就绪')}
async function apiGet(endpoint,params={}){const b=getBridge();if(!b||typeof b.apiGet!=='function')throw new Error('Bridge 未就绪');return b.apiGet(endpoint,params)}
async function apiPost(endpoint,body={}){const b=getBridge();if(!b||typeof b.apiPost!=='function')throw new Error('Bridge 未就绪');return b.apiPost(endpoint,body)}
const $=s=>document.querySelector(s);const state={personas:[],current:'',providers:[],primary:'',dirty:false,quotaDirty:false,quotas:[],quotaPolicy:{},rebuilding:false,selectedReferences:new Set(),optimizerProviderId:'',visionProviderId:''};
function notify(message,error=false){const el=$('#notice');el.textContent=message||'';el.style.color=error?'var(--danger)':'var(--primary)'}
function escapeHtml(value){const el=document.createElement('div');el.textContent=String(value);return el.innerHTML}
function lineList(value){const values=Array.isArray(value)?value:String(value||'').split(/\r?\n/);return values.map(item=>String(item).trim()).filter(Boolean)}
function hasApiKeys(item){return lineList(item.api_keys).length>0||Boolean(item.api_keys_configured)}
function updateDirtyClass(){document.body.classList.toggle('provider-dirty',state.dirty);document.body.classList.toggle('quota-dirty',state.quotaDirty)}
function setDirty(value=true){state.dirty=value;$('#save-config').disabled=!value;updateDirtyClass()}
function setQuotaDirty(value=true){state.quotaDirty=value;$('#save-quotas').disabled=!value;updateDirtyClass()}
function filteredPersonas(){const q=$('#persona-search').value.trim().toLowerCase();return state.personas.filter(id=>id.toLowerCase().includes(q))}
function renderPersonaOptions(){const items=filteredPersonas();$('#persona-select').innerHTML=items.map(id=>`<option value="${escapeHtml(id)}"${id===state.current?' selected':''}>${escapeHtml(id)}</option>`).join('')}
async function loadPersonas(){const result=await apiGet('personas');state.personas=(result.personas||[]).map(item=>item.id);renderPersonaOptions();if(state.personas.length){state.current=state.personas[0];renderPersonaOptions();await loadPersonaDetail()}}
async function loadPersonaDetail(){if(!state.current)return;notify('正在读取 Persona……');const result=await apiGet('detail',{persona_id:state.current});if(!result.success)throw new Error(result.message||'读取失败');$('#persona-title').textContent=state.current;$('#persona-prompt').textContent=result.prompt||'空 prompt';$('#persona-summary').value=result.summary||'';updateSummaryCount();$('#summary-mode').textContent=result.summary?result.summary_manual?'手工覆写':'自动摘要':'';$('#rebuild').disabled=state.rebuilding;$('#upload').disabled=false;$('#save-summary').disabled=false;await renderGallery(result.references||[]);notify('')}
async function renderGallery(refs){const gallery=$('#gallery');state.selectedReferences.clear();if(!refs.length){gallery.innerHTML='<p class="empty">尚无参考图</p>';return}const cards=[];for(const ref of refs){try{const preview=await apiGet('preview',{persona_id:state.current,filename:ref.name});cards.push(`<div class="image-card"><label class="reference-select"><input type="checkbox" data-reference="${escapeHtml(ref.name)}"><span>用于本次识图</span></label>${preview.success?`<img src="${preview.data_url||`data:${preview.mime_type};base64,${preview.base64_data}`}" alt="Persona 参考图">`:`<div class="preview-error">${escapeHtml(preview.message||'预览失败')}</div>`}<button type="button" data-delete="${escapeHtml(ref.name)}">删除这张图</button></div>`)}catch(error){cards.push(`<div class="image-card"><label class="reference-select"><input type="checkbox" data-reference="${escapeHtml(ref.name)}"><span>用于本次识图</span></label><div class="preview-error">预览请求失败</div><button type="button" data-delete="${escapeHtml(ref.name)}">删除这张图</button></div>`)}}gallery.innerHTML=cards.join('')}
function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
function chevron(){return '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg>'}
function renderProviders(){const root=$('#provider-list');if(!state.providers.length){root.innerHTML='<p class="empty">尚未添加图片生成节点。</p>';return}root.innerHTML=state.providers.map((item,index)=>{const primary=item.id===state.primary;const tooltip=primary?'':`title="设置为主节点"`;return `<article class="provider-node" data-index="${index}"><div class="node-main"><button class="primary-toggle ${primary?'active':item.complete?'complete':'incomplete'}" data-primary="${index}" ${tooltip} aria-label="${primary?'主节点':'设置为主节点'}">${primary?'★':'●'}</button><div><div class="provider-title-line"><strong>${escapeHtml(item.id)}</strong>${primary?'<span class="dirty-mark">未保存</span>':''}</div><div class="node-meta">顺序 ${index+1} · ${escapeHtml(item.api_type||'未选接口')} · ${escapeHtml(item.model||'未填模型')}</div></div><button class="expand-button" data-expand="${index}" aria-label="展开节点配置">${chevron()}</button></div><div class="node-fields"><label>节点 ID<input data-field="id" value="${escapeHtml(item.id||'')}"></label><label>API Key（每行一个）${item.api_keys_configured?' · 已配置':''}<textarea rows="3" data-field="api_keys" placeholder="每行一个 API Key" spellcheck="false"></textarea></label><label>Base URL<input data-field="base_url" value="${escapeHtml(item.base_url||'')}"></label><label>类型<select data-field="api_type">${['openai_image','openai_chat','gemini_official','dashscope_multimodal','custom_endpoint'].map(v=>`<option value="${v}" ${v===item.api_type?'selected':''}>${v}</option>`).join('')}</select></label><label>主模型<input data-field="model" value="${escapeHtml(item.model||'')}"></label><label>参考图总上限（0=不限）<input type="number" min="0" step="1" data-field="reference_image_limit" value="${Math.max(0,Number(item.reference_image_limit)||0)}"></label><label>备用模型<textarea rows="3" data-field="available_models">${escapeHtml((item.available_models||[]).join('\n'))}</textarea></label><label>超时（秒）<input type="number" min="10" data-field="timeout" value="${Number(item.timeout)||180}"></label><label>尺寸<input data-field="default_size" value="${escapeHtml(item.default_size||'1024x1024')}"></label></div></article>`}).join('')}
function renderChatProviderOptions(items){const options=['<option value="">留空</option>',...items.map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml(item.id)}${item.model?` · ${escapeHtml(item.model)}`:''}</option>`)].join('');$('#optimizer-provider').innerHTML=options;$('#vision-provider').innerHTML=options;$('#optimizer-provider').value=state.optimizerProviderId;$('#vision-provider').value=state.visionProviderId}
async function loadProviders(){const result=await apiGet('providers');state.providers=(result.providers||[]).map(item=>({...item,api_keys:[]}));state.primary=result.primary_provider_id||'';state.optimizerProviderId=result.optimizer_provider_id||'';state.visionProviderId=result.vision_provider_id||'';renderChatProviderOptions(result.chat_providers||[]);renderProviders();setDirty(false)}
function quotaStatus(item){const tags=[];if(item.blocked)tags.push('<span class="blocked">黑名单</span>');else if(item.unlimited)tags.push('<span class="unlimited">无限额度</span>');else tags.push('<span>普通用户</span>');return tags.join('')}
function renderQuotaPolicy(){const p=state.quotaPolicy;$('#quota-policy').innerHTML=[`<span>额度限制：${p.quota_enabled?'开启':'关闭'}</span>`,`<span>每日刷新：${p.daily_refresh_enabled?`重置为 ${Number(p.daily_quota_target)||0}`:'关闭'}</span>`,`<span>签到：${p.checkin_enabled?`${Number(p.checkin_quota_min)||0}–${Number(p.checkin_quota_max)||0}`:'关闭'}</span>`].join('')}
function renderQuotas(){const root=$('#quota-list');if(!state.quotas.length){root.innerHTML='<p class="empty" style="padding:14px">暂无额度记录，可点击“新增 ID”。</p>';$('#quota-count').textContent='0 条记录';return}root.innerHTML=state.quotas.map((item,index)=>`<div class="quota-row" role="row" data-quota-index="${index}"><input data-quota-field="user_id" value="${escapeHtml(item.user_id||'')}" placeholder="用户 ID" ${item.isNew?'':'readonly'}><div class="quota-status">${quotaStatus(item)}</div><div class="number-stepper"><input type="number" min="0" step="1" data-quota-field="quota" value="${Math.max(0,Number(item.quota)||0)}"><div class="step-buttons"><button type="button" data-quota-step="1" aria-label="增加额度">▲</button><button type="button" data-quota-step="-1" aria-label="减少额度">▼</button></div></div><span>${escapeHtml(item.last_refresh_date||'—')}</span><span>${escapeHtml(item.last_checkin_date||'—')}</span></div>`).join('');$('#quota-count').textContent=`${state.quotas.length} 条记录`}
async function loadQuotas(){const result=await apiGet('quotas');if(!result.success)throw new Error(result.message||'读取额度失败');state.quotas=(result.quotas||[]).map(item=>({...item,isNew:false}));state.quotaPolicy=result;renderQuotaPolicy();renderQuotas();setQuotaDirty(false)}
function syncQuotaField(target){const row=target.closest('[data-quota-index]');if(!row)return;const item=state.quotas[Number(row.dataset.quotaIndex)];if(target.dataset.quotaField==='quota'){item.quota=Math.max(0,Math.trunc(Number(target.value)||0));target.value=item.quota}else item.user_id=target.value.trim();setQuotaDirty(true)}
async function saveQuotas(){const ids=state.quotas.map(item=>String(item.user_id||'').trim());if(ids.some(id=>!id)){notify('用户 ID 不能为空',true);return}if(new Set(ids).size!==ids.length){notify('用户 ID 不能重复',true);return}const result=await apiPost('quotas/save',{quotas:state.quotas.map(item=>({user_id:String(item.user_id).trim(),quota:Math.max(0,Math.trunc(Number(item.quota)||0))}))});notify(result.message,!result.success);if(result.success)await loadQuotas()}
function updateSummaryCount(){const area=$('#persona-summary');$('#summary-count').textContent=`${area.value.length} 字符`}
function setRebuildLoading(active){state.rebuilding=active;const button=$('#rebuild');button.disabled=active||!state.current;button.classList.toggle('is-loading',active);button.setAttribute('aria-busy',active?'true':'false');button.textContent=active?'正在重建…':'重建外观摘要'}
function syncProviderField(target){const node=target.closest('.provider-node');if(!node)return;const item=state.providers[Number(node.dataset.index)];const oldId=item.id;item[target.dataset.field]=['available_models','api_keys'].includes(target.dataset.field)?lineList(target.value):target.type==='number'?Number(target.value):target.value;if(target.dataset.field==='id'&&state.primary===oldId)state.primary=item.id;item.complete=Boolean(item.id&&item.base_url&&hasApiKeys(item));setDirty(true);renderStatusOnly(node,item)}
function renderStatusOnly(node,item){const toggle=node.querySelector('.primary-toggle');if(toggle.classList.contains('active'))return;toggle.classList.toggle('complete',item.complete);toggle.classList.toggle('incomplete',!item.complete)}
async function saveProviderConfig(){const result=await apiPost('providers/save',{primary_provider_id:state.primary,optimizer_provider_id:state.optimizerProviderId,vision_provider_id:state.visionProviderId,providers:state.providers.map(item=>({id:item.id,api_type:item.api_type,base_url:item.base_url,api_keys:lineList(item.api_keys),model:item.model,reference_image_limit:Math.max(0,Math.trunc(Number(item.reference_image_limit)||0)),available_models:lineList(item.available_models),timeout:item.timeout,default_size:item.default_size}))});notify(result.message,!result.success);if(result.success)await loadProviders()}
document.addEventListener('click',async event=>{const tab=event.target.closest('[data-tab]');if(tab){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${tab.dataset.tab}`));$('#save-config').hidden=tab.dataset.tab==='quotas';if(tab.dataset.tab==='providers'&&!state.providers.length)await loadProviders().catch(e=>notify(e.message,true));if(tab.dataset.tab==='quotas'&&!state.quotas.length)await loadQuotas().catch(e=>notify(e.message,true));return}const step=event.target.closest('[data-quota-step]');if(step){const row=step.closest('[data-quota-index]');const item=state.quotas[Number(row.dataset.quotaIndex)];item.quota=Math.max(0,(Number(item.quota)||0)+Number(step.dataset.quotaStep));row.querySelector('[data-quota-field="quota"]').value=item.quota;setQuotaDirty(true);return}const primary=event.target.closest('[data-primary]');if(primary){state.primary=state.providers[Number(primary.dataset.primary)].id;setDirty(true);renderProviders();return}const expand=event.target.closest('[data-expand]');if(expand){expand.closest('.provider-node').classList.toggle('expanded');return}const deleteButton=event.target.closest('[data-delete]');if(deleteButton){deleteButton.disabled=true;const r=await apiPost('delete',{persona_id:state.current,filename:deleteButton.dataset.delete});notify(r.message,!r.success);if(r.success)await loadPersonaDetail();else deleteButton.disabled=false}})
$('#provider-list').addEventListener('input',event=>{if(event.target.dataset.field)syncProviderField(event.target)});$('#provider-list').addEventListener('change',event=>{if(event.target.dataset.field)syncProviderField(event.target)});$('#save-config').addEventListener('click',()=>saveProviderConfig().catch(e=>notify(e.message,true)));
$('#add-provider').addEventListener('click',()=>{let number=state.providers.length+1;let id=`provider_${number}`;const ids=new Set(state.providers.map(item=>item.id));while(ids.has(id)){number+=1;id=`provider_${number}`}state.providers.push({id,api_type:'openai_image',model:'',reference_image_limit:0,available_models:[],base_url:'',api_keys:[],api_keys_configured:false,default_size:'1024x1024',timeout:180,complete:false});if(!state.primary)state.primary=id;setDirty(true);renderProviders();const node=$('#provider-list .provider-node:last-child');if(node)node.classList.add('expanded')});
$('#quota-list').addEventListener('input',event=>{if(event.target.dataset.quotaField)syncQuotaField(event.target)});$('#quota-list').addEventListener('change',event=>{if(event.target.dataset.quotaField)syncQuotaField(event.target)});$('#add-quota-row').addEventListener('click',()=>{state.quotas.push({user_id:'',quota:0,blocked:false,unlimited:false,last_refresh_date:'',last_checkin_date:'',isNew:true});renderQuotas();setQuotaDirty(true);const inputs=document.querySelectorAll('#quota-list [data-quota-field="user_id"]');if(inputs.length)inputs[inputs.length-1].focus()});
$('#save-quotas').addEventListener('click',()=>saveQuotas().catch(e=>notify(e.message,true)));
$('#gallery').addEventListener('change',event=>{const name=event.target.dataset.reference;if(!name)return;if(event.target.checked)state.selectedReferences.add(name);else state.selectedReferences.delete(name)});$('#optimizer-provider').addEventListener('change',event=>{state.optimizerProviderId=event.target.value;setDirty(true)});$('#vision-provider').addEventListener('change',event=>{state.visionProviderId=event.target.value;setDirty(true)});
$('#persona-search').addEventListener('input',renderPersonaOptions);$('#persona-select').addEventListener('change',async event=>{state.current=event.target.value;await loadPersonaDetail().catch(e=>notify(e.message,true))});
$('#rebuild').addEventListener('click',async()=>{if(state.rebuilding||!state.current)return;const personaId=state.current;setRebuildLoading(true);try{const r=await apiPost('rebuild',{persona_id:personaId,reference_names:[...state.selectedReferences]});if(!r.success){notify(r.message||'重建失败',true);return}if(state.current===personaId)await loadPersonaDetail();notify(r.message||'外观摘要已重建')}catch(error){notify(error.message||'重建失败',true)}finally{setRebuildLoading(false)}});
$('#persona-summary').addEventListener('input',updateSummaryCount);$('#save-summary').addEventListener('click',async()=>{const summary=$('#persona-summary').value.trim();if(!summary){notify('外观摘要不能为空',true);return}const r=await apiPost('summary',{persona_id:state.current,summary});notify(r.message,!r.success);if(r.success)await loadPersonaDetail()});
$('#upload').addEventListener('click',async()=>{const files=[...$('#reference-files').files];if(!files.length){notify('请先选择图片',true);return}const images=[];for(const file of files)images.push({mime_type:file.type,data:await readFile(file)});const r=await apiPost('upload',{persona_id:state.current,images});notify(r.message,!r.success);if(r.success){$('#reference-files').value='';await loadPersonaDetail()}});
window.addEventListener('beforeunload',event=>{if(!state.dirty&&!state.quotaDirty)return;event.preventDefault();event.returnValue=''});
(async()=>{try{await waitBridge();const bridge=getBridge();if(bridge&&typeof bridge.onContext==='function')bridge.onContext(context=>{if(typeof context?.isDark==='boolean')document.documentElement.dataset.theme=context.isDark?'dark':'light'});await Promise.all([loadPersonas(),loadProviders(),loadQuotas()])}catch(error){notify(error.message||'页面初始化失败',true)}})();
